name: Bug 反馈
description: "报告一个 Bug 或异常行为"
title: "[Bug] "
labels: ["bug"]
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: 提交前确认
      description: 请确保已完成以下步骤，否则 Issue 可能会被直接关闭。
      options:
        - label: 我已搜索过现有 Issue，确认没有重复问题
          required: true
        - label: 如果是前端问题，我已在无痕模式（禁用所有扩展）下复现，问题仍然存在
          required: true
        - label: 此Issue仅包含一个Bug反馈，而不是多个Bug反馈
          required: true
  - type: textarea
    attributes:
      label: 问题描述
      description: 请详细描述遇到的问题。如涉及前端问题，请务必在无痕模式下截图，否则 Issue 可能会被关闭。
      placeholder: 清晰描述你遇到了什么问题...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 复现步骤
      description: 请提供能够复现该问题的详细步骤
      placeholder: |
        1. 进入 '...'
        2. 点击 '...'
        3. 滚动至 '...'
        4. 出现错误
    validations:
      required: true
  - type: textarea
    attributes:
      label: 相关日志
      description: WEB端的请求日志和后端控制台日志
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: 环境信息
      description: 请提供浏览器版本、操作系统等相关环境信息
      placeholder: |
        - 浏览器: Chrome 120.0.xxx
        - 操作系统: Windows 11 / macOS 14.x / Ubuntu 22.04
      render: shell
    validations:
      required: true